# Cybersecurity at Scale

### Keywords
cybersecurity, enterprise, networking, malware, detection

## Throwing Money at the Problem
A typical enterprise views cybersecurity as a silent menace. A problem that is always at the back of their mind but is never truly urgent until it breaks. Constant news of enterprise data breaches reinforce the fear, and companies invest just enough to give their leadership a sense of security. That feeling of security is achieved by adding more layers of security, spending more time and capital on each layer, and constantly updating and testing each layer.

## Better Way Through Data Science
While a good cybersecurity strategy will always be a full stack solution, most layers (particularly those closest to the hardware) often rely on deterministic means to provide security. A virus scan program might store hashes of known malware, an automated administrator applies the latest security patches, or a firewall prevents access to a network on all but a few ports. While good strategies, these deterministic systems depend on human judgement that is often not reevaluated frequently. There is an opportunity for an umbrella layer of cybersecurity to protect entire systems, a layer that can learn and adapt to new attacks. Better yet, if this layer could protect against zero-day vulnerabilities in would be invaluable.

There is currently basic research attempting to do exactly that on a limited scope [looking for citation]. By looking at all traffic passing through an enterprise network, some content could be flagged as potentially malicious and stopped before it touches a vulnerable system. One existing approach to do exactly this involves inspecting packets for machine code. Since machine code follows a very rigid language, it is easy to identify a few consecutive lines that represent a block of valid code. This network traffic is then analyzed since it is likely to be either malicious or part of a very small percent of legal traffic containing machine code. The analysis searches this code for patterns that match common malware, and blocks the traffic if there is a match.
While there is a lot of potential in this security system, tremendous value could be added by taking it a step further. The system described in the previous paragraph depends on a knowledge of the target machines low-level language, and this is not scalable across an entire enterprise. However it would be possible to transform that step from an algorithmic approach to a data science approach. Taking all existing malware and training a model to classify all network traffic as either benign or potentially malicious could eliminate the first deterministic approach. The second step makes the same stochastic judgement about the potential danger of network traffic.

## A Business Imperative
The enterprise market for this dynamic cybersecurity umbrella is enormous. In conjunction with existing security techniques, it would make existing enterprises far more resilient to attacks by blocking malicious traffic before it reaches the corporate intranet. IT professionals would be foolish not to incorporate this layer into their overall security strategy.

## First Headline Attempt
Enterprises safe fom malware using network scanning: CEO still writes passwords on sticky notes

## Summarized Peer Feedback
Throwing Money at the Problem
- Add supporting evidence (Charlene)
- Unclear if enterprise is spending too much or too little (Simon)
Better Way Through Data Science
- Make technical explanation more concise (Akhil and Charlene)
- Add a better description of what machine code means and how data science would be applied (Akhil)
A Business Imperative
- How does this scale up, or is it always an enterprise-specific solution? (Akhil)
